version: 2.1
jobs:
  build:
    docker:
      - image: docker/tilt:latest

    steps:
      - checkout
      - setup_remote_docker
      - run: apt update && apt install -y openjdk-17-jdk unzip rsync python3
      - run: ctlptl create cluster kind --registry=ctlptl-registry && test/test.sh
