version: 2.1
jobs:
  build:
    docker:
      - image: tiltdev/tilt:latest

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: apt update && apt install -y openjdk-11-jdk unzip rsync python
      - run: ctlptl create cluster kind --registry=ctlptl-registry && test/test.sh
