version: 2.1
jobs:
  build:
    docker:
      - image: tiltdev/tilt:latest

    steps:
      - setup_remote_docker
      - checkout
      - run: echo "deb http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list
      - run: apt update && apt install -y openjdk-8-jdk unzip rsync python
      - run: with-kind-cluster.sh test/test.sh