# -*- mode: Python -*-

# Records the current time, then kicks off a server update.
# Normally, you would let Tilt do deploys automatically, but this
# shows you how to set up a custom workflow that measures it.
local_resource(
    'deploy',
    'python3 record-start-time.py',
)

gradlew = "./gradlew"
if os.name == "nt":
  gradlew = "gradlew.bat"

local_resource(
  'example-java-compile',
  gradlew + ' bootJar',
  deps=['src', 'build.gradle'],
  resource_deps = ['deploy'])

docker_build(
  'example-java-image',
  './build/libs',
  dockerfile='./Dockerfile')

k8s_yaml('kubernetes.yaml')
k8s_resource('example-java', port_forwards=8000,
             resource_deps=['deploy', 'example-java-compile'])
