# -*- mode: Python -*-

docker_build(
  'quarkus-sync-image',
  '.',
  dockerfile='./src/main/docker/Dockerfile.jvm',
  live_update=[
    sync('./target/*.jar','/deployments/app.jar'),
  ])

k8s_yaml('src/main/kubernetes/app.yaml')
k8s_resource('quarkus-sync-demo', port_forwards=[8080,5005])
