# -*- mode: Python -*-

# Records the current time, then kicks off a server update.
# Normally, you would let Tilt do deploys automatically, but this
# shows you how to set up a custom workflow that measures it.
local_resource(
    'deploy',
    './record-start-time.sh',
)

local_resource(
  'example-java-compile',
  './gradlew bootJar && ' +
  'unzip -o build/libs/example-0.0.1-SNAPSHOT.jar -d build/jar-staging && ' +
  'rsync --inplace --checksum -r build/jar-staging/ build/jar',
  deps=['src', 'build.gradle'],
  resource_deps = ['deploy'])

docker_build(
  'example-java-image',
  './build/jar',
  dockerfile='./Dockerfile',
  live_update=[
    sync('./build/jar/BOOT-INF/lib', '/app/lib'),
    sync('./build/jar/META-INF', '/app/META-INF'),
    sync('./build/jar/BOOT-INF/classes', '/app'),
  ],
  entrypoint = 'find . | entr -r java -noverify -cp .:./lib/* dev.tilt.example.ExampleApplication')

k8s_yaml('kubernetes.yaml')
k8s_resource('example-java', port_forwards=8000,
             resource_deps=['deploy', 'example-java-compile'])
